#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  project: src/Aida.Application/Aida.Application.csproj # path to Visual Studio solution or project

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing entire folder as a zip archive
  - path: src/Aida.Application/bin/Release
    name: last
